#' Return the mean squared error between the observed counts and the predicted ones for all the configurations considered during cross 
#' validation. This function expects an input object as the one generated by the function nmf.LassoCV.
#' @title as.mean.squared.error
#' @param nmf.LassoCV.result results of cross validation into an object as the one generated by the function nmf.LassoCV
#' @return A list of matrices with mean squared error values computed between the observed counts and the predicted ones at each iteration 
#' of cross validation
#' @export as.mean.squared.error
#'
"as.mean.squared.error" <- function( nmf.LassoCV.result ) {

    return(nmf.LassoCV.result$mean_squared_error)
    
}

#' Return the discovered alpha values for a given configuration from an input object as the one generated by the function evaluate.lambda.range.
#' @title as.alpha.in.range
#' @param lambda.range.result discovered signatures into an object as the one generated by the function evaluate.lambda.range
#' @param lambda_value value of LASSO used for the estimation whose configuration has to be returned
#' @return A matrix with alpha values
#' @export as.alpha.in.range
#'
"as.alpha.in.range" <- function( lambda.range.result, lambda_value = 0.20 ) {

    nmf.LassoK.result = lambda.range.result[[1,paste0(as.character(lambda_value),"_lambda")]]
    return(nmf.LassoK.result$alpha)
    
}

#' Return the discovered signatures (beta values) for a given configuration from an input object as the one generated by the function evaluate.lambda.range.
#' @title as.beta.in.range
#' @param lambda.range.result discovered signatures into an object as the one generated by the function evaluate.lambda.range
#' @param lambda_value value of LASSO used for the estimation whose configuration has to be returned
#' @return A matrix with beta values
#' @export as.beta.in.range
#'
"as.beta.in.range" <- function( lambda.range.result, lambda_value = 0.20 ) {

    nmf.LassoK.result = lambda.range.result[[1,paste0(as.character(lambda_value),"_lambda")]]
    return(nmf.LassoK.result$beta)
    
}

#' Return the initial values of beta used for the estimation of the signatures for a given configuration from an input object as the one generated by the 
#' function evaluate.lambda.range.
#' @title as.starting.beta.in.range
#' @param lambda.range.result discovered signatures into an object as the one generated by the function nmf.LassoK
#' @param lambda_value value of LASSO used for the estimation whose configuration has to be returned
#' @return A matrix with the initial values of beta used for the estimation of the signatures
#' @export as.starting.beta.in.range
#'
"as.starting.beta.in.range" <- function( lambda.range.result, lambda_value = 0.20 ) {

    nmf.LassoK.result = lambda.range.result[[1,paste0(as.character(lambda_value),"_lambda")]]
    return(nmf.LassoK.result$starting_beta)
    
}

#' Return the log-likelihood values for a given configuration for each iteration during the estimation of the signatures from an input object as the one 
#' generated by the function evaluate.lambda.range.
#' @title as.loglik.progression.in.range
#' @param lambda.range.result discovered signatures into an object as the one generated by the function evaluate.lambda.range
#' @param lambda_value value of LASSO used for the estimation whose configuration has to be returned
#' @return A vector with log-likelihood values for each iteration during the estimation of the signatures
#' @export as.loglik.progression.in.range
#'
"as.loglik.progression.in.range" <- function( lambda.range.result, lambda_value = 0.20 ) {

    nmf.LassoK.result = lambda.range.result[[1,paste0(as.character(lambda_value),"_lambda")]]
    return(nmf.LassoK.result$loglik_progression)
    
}

#' Return the discovered alpha values from an input object as the one generated by the function nmf.LassoK.
#' @title as.alpha
#' @param nmf.LassoK.result discovered signatures into an object as the one generated by the function nmf.LassoK
#' @return A matrix with alpha values
#' @export as.alpha
#'
"as.alpha" <- function( nmf.LassoK.result ) {
    
    return(nmf.LassoK.result$alpha)
    
}

#' Return the discovered signatures (beta values) from an input object as the one generated by the function nmf.LassoK.
#' @title as.beta
#' @param nmf.LassoK.result discovered signatures into an object as the one generated by the function nmf.LassoK
#' @return A matrix with beta values
#' @export as.beta
#'
"as.beta" <- function( nmf.LassoK.result ) {
    
    return(nmf.LassoK.result$beta)
    
}

#' Return the initial values of beta used for the estimation of the signatures from an input object as the one generated by the function nmf.LassoK.
#' @title as.starting.beta
#' @param nmf.LassoK.result discovered signatures into an object as the one generated by the function nmf.LassoK
#' @return A matrix with the initial values of beta used for the estimation of the signatures
#' @export as.starting.beta
#'
"as.starting.beta" <- function( nmf.LassoK.result ) {
    
    return(nmf.LassoK.result$starting_beta)
    
}

#' Return the log-likelihood values for each iteration during the estimation of the signatures from an input object as the one generated by 
#' the function nmf.LassoK.
#' @title as.loglik.progression
#' @param nmf.LassoK.result discovered signatures into an object as the one generated by the function nmf.LassoK
#' @return A vector with log-likelihood values for each iteration during the estimation of the signatures
#' @export as.loglik.progression
#'
"as.loglik.progression" <- function( nmf.LassoK.result ) {
    
    return(nmf.LassoK.result$loglik_progression)
    
}
